### ISSUE TITLE
Issues unloading

### ISSUE THREAD

**Issue by clavicus-zz** [VertexDezign/TargetFillLevel#7] opened 2024-09-20 19:01 UTC
Haven’t seen this mod before, seems really nice when it was working. Love the extra UI info.
Installed yesterday on my hoff bergmann save and ran into two issues before I had to uninstall.

had LUA issues when pouring food into pig pen. Didn’t try with multiple inplements. Was using a ruby front loader. 
also and LUA errors and freezing when pouring milk into calf igloos with farmer Andy universal liquid trailer. Wasn’t using his camlock add on. So, standard unloading. 
i feel like I saw some other strangeness too for the short while I had it installed. Generally felt unloading or overloading got weird. Might have only been with placables though.

**Comment by schliesser** [comment] 2024-09-20 21:19
Heyho @clavicus-zz 
thank you very much for trying out that mod and reporting the issues.

The version 2.0.1.0 had issues in general with the unloading triggers for animal husbandaries. Therefore a hotfix was released today: v2.0.1.1 which is already available in the ModHub.

Can you give us a second chance and try the new version again? ;-)

> i feel like I saw some other strangeness too for the short while I had it installed. Generally felt unloading or overloading got weird. Might have only been with placables though.

I'm curious to learn more about that strangeness if it still exists with the latest version?

Have a nice day

**Comment by schliesser** [comment] 2024-09-20 21:20
Mark as duplicate of #4

**Comment by clavicus-zz** [comment] 2024-09-21 11:48
> Heyho @clavicus-zz thank you very much for trying out that mod and reporting the issues.
> 
> The version 2.0.1.0 had issues in general with the unloading triggers for animal husbandaries. Therefore a hotfix was released today: v2.0.1.1 which is already available in the ModHub.
> 
> Can you give us a second chance and try the new version again? ;-)
> 
> > i feel like I saw some other strangeness too for the short while I had it installed. Generally felt unloading or overloading got weird. Might have only been with placables though.
> 
> I'm curious to learn more about that strangeness if it still exists with the latest version?
> 
> Have a nice day

I downloaded the new version and tested the things that had caused me issues and it looks like it’s all cleared up! Thank you! Love the new UI feature

**Closed** 2024-09-21 11:48 UTC
Labels: bug, duplicate
